version: '2'

services:
  rabbitmq-management:
    image: rabbitmq:3-management
    container_name: cloud-native-ch10-messaging-rabbitmq-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672